server {
    listen 127.0.0.1:8090;
    server_name default.local;
    root www;
    index index.html;

    route / {
        methods GET;
    }
}

server {
    listen 127.0.0.1:8090;
    server_name test.com;
    root www/demo;
    index index.html;

    route / {
        methods GET;
    }
}
